{
# This file is automatically generated, do not edit UNLESS you are adding a _new_ project
  "client-ip" = {
    url = "https://github.com/outskirtslabs/client-ip.git";
    rev = "9fb38833d1fea8c1b4d7902382216557b6a2a078";
    hash = "sha256-oqme7JBdtslomTMU978cM/rLJKsRQYar2Jv+T6OU72o=";
    refs_hash = "sha256-LVxa0AZ7Fh1tHRndGtKqGPuT70kK2GXS2goCTjRwvFU=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "datahike-sqlite" = {
    url = "https://github.com/outskirtslabs/datahike-sqlite.git";
    rev = "2c9e1a08e50d98edab03821ec1ee33f1e3397e40";
    hash = "sha256-CKFj4Yvt9zGcpQ/L/mofU8g+XWBOEr+hSklUGwUfhEs=";
    refs_hash = "sha256-xgrUj8/ka+1axGCcOr1SYodPIOngKzMv41oo3FcpgxA=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "datastar-expressions" = {
    url = "https://github.com/outskirtslabs/datastar-expressions.git";
    rev = "4cd3ce7ab1616980c7df265ee4138ae04a45520d";
    hash = "sha256-1okNIvE2QiWubJ6PjfpCtrfR/3MT4cHeHMocFhCCs/E=";
    refs_hash = "sha256-PmNWPvIQ7wdfYwwFEEncFs3bQI6DhCcNWO/YvS6sycU=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "datomic-pro-flake" = {
    url = "https://github.com/outskirtslabs/datomic-pro-flake.git";
    rev = "50d321c5e9d314e3bf474bcc931073a012c74df4";
    hash = "sha256-9HYfYjZMDL2PZXBRYzCIX40H3uM7TuprFYLyPDDAiIo=";
    refs_hash = "sha256-JOhE9l3xPxJbu9Q09huzwylVmouEHwlu1WdtSpKl4rg=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "h2o-zig" = {
    url = "https://github.com/outskirtslabs/h2o-zig.git";
    rev = "a77dcf5b57287d6f3216b6bc485f8baafd478e65";
    hash = "sha256-FxoKa+1Ts4wal3c2bAfLLCLKdxhez4Wq1fuBgBa5OXE=";
    refs_hash = "sha256-3GfLxOHO28QuGUa/KcwszMMHper416oqO3uHL9si0NA=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "nixos-hetzner" = {
    url = "https://github.com/outskirtslabs/nixos-hetzner.git";
    rev = "02413100fe30e53cc9c8474dac6c7259151eb22b";
    hash = "sha256-63wgWHIlLup/jALiHjba+Yn0qR59dk0CBAJEfG59tE0=";
    refs_hash = "sha256-dMOFu6Jw2fdec37AGXhage3zAigXd+RErOhwDBaLG8g=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "nixos-hetzner-demo" = {
    url = "https://github.com/outskirtslabs/nixos-hetzner-demo.git";
    rev = "37e803e2adfb1f22f4d16ddf3fb572d9ba74bfc6";
    hash = "sha256-M96XICR3lzW67lWmrewkF7XNO3pI7R+kBmlClEPLSHQ=";
    refs_hash = "sha256-g8rqzzoHiE27Jd6uuYmodFKXm/Qrb8B8Sn7YNUqjKzk=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "ol.clave" = {
    url = "https://github.com/outskirtslabs/clave.git";
    rev = "98b5e18beb51e03e1855a47757ad83b311a20dae";
    hash = "sha256-dDyxLEJG3m72H53P1ofqih06q/niOIxGWdIFSO3WDsI=";
    refs_hash = "sha256-i9BGcL7G56ZxHlvVBOMVPfFxczOO9g6RLtbeNUuwG2I=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "ol.dirs" = {
    url = "https://github.com/outskirtslabs/dirs.git";
    rev = "bb1cfa4597e4cd3c26b3c4050d45877a3d47ed93";
    hash = "sha256-wb0MZAvUyKMnUNFgE1IsycvRNgbXqbLcPfRZFwzWSWM=";
    refs_hash = "sha256-d9aQW367qXUWalnUcvODz5Vat9Mh9XNOkO/fiPDhI30=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "ol.llx" = {
    url = "https://github.com/outskirtslabs/llx.git";
    rev = "9abc4b1e63060e2a6e407ea4631da69883521dc5";
    hash = "sha256-AZH3eu45ZVTGdb16j7hHCaKYxzDu9pUenMfXVeBMmcg=";
    refs_hash = "sha256-F9NJP8y0Gnw8VQBXvtZT69XDH/l0dDOaNPaB0klo9V0=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "ol.sfv" = {
    url = "https://github.com/outskirtslabs/sfv.git";
    rev = "1550fda6f15622792dae3e43b51d9598310aacd2";
    hash = "sha256-bR9aFiWnQTXlz9iQtW2gCT0mQ5grkOETBt5DYORB720=";
    refs_hash = "sha256-tL0rM9b3Zfe7vBuqFP7uAqR9BOkAIFO8CKIWVRTunvA=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "ol.sops" = {
    url = "https://github.com/outskirtslabs/sops.git";
    rev = "63afc84d7293340c005c9abdebec50c5349ba370";
    hash = "sha256-4luefKbhU8oaV5OiApT3GhCIUhk3qWvZrId4bExnS0U=";
    refs_hash = "sha256-3B7Tx/5RmCmw2ucVG+boNxXk65QsWe0jXTcBu1R/Pbg=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "ol.trixnity" = {
    url = "https://github.com/outskirtslabs/trixnity-clj.git";
    rev = "e8e73b4aa598e8e04f9ad8f7451408952531ce9d";
    hash = "sha256-BVGVsfJouCrQ8Ril+1NE2eso5nc01AgUY1XjHz3otw0=";
    refs_hash = "sha256-55aAQ+CfCWxTpYB/NnhSy4nJc4vcneu/6k9VKCHm0w0=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "ol.vips" = {
    url = "https://github.com/outskirtslabs/vips.git";
    rev = "afdf1f7a5184a8078fb567569f7657501dac42df";
    hash = "sha256-bUGbL13VA7HCgkQG7GoMKIVsgsA9tXmm4qQh1gTQNhU=";
    refs_hash = "sha256-ZjdCUGduXpbS3uwm5SMM9tuRZfiMqt47BSx3pLBjQEA=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };
}
