{
# This file is automatically generated, do not edit UNLESS you are adding a _new_ project
  "client-ip" = {
    url = "https://github.com/outskirtslabs/client-ip.git";
    rev = "9fb38833d1fea8c1b4d7902382216557b6a2a078";
    hash = "sha256-oqme7JBdtslomTMU978cM/rLJKsRQYar2Jv+T6OU72o=";
    refs_hash = "sha256-LVxa0AZ7Fh1tHRndGtKqGPuT70kK2GXS2goCTjRwvFU=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "datahike-sqlite" = {
    url = "https://github.com/outskirtslabs/datahike-sqlite.git";
    rev = "ef9c39f3d56b7f4e4e42831a57b6ed6254da5f15";
    hash = "sha256-2C/wboRfjMd54VutafDLHy4CBx+T89Vc6lU53SBu6eY=";
    refs_hash = "sha256-v6zHYvXrQtnf7WYbPj/hMIjWItx8/2XQHGDw1NBuJx0=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "datastar-expressions" = {
    url = "https://github.com/outskirtslabs/datastar-expressions.git";
    rev = "e8f9543daacef39a11ab58641aeef96d31be381d";
    hash = "sha256-3TqQv0kxBpjb2ZocNuSHHYqUut/PnUnHaUyVHl6oOVs=";
    refs_hash = "sha256-cDkZyRwSKnWyGrEburOU4tEYK/G+jWsrOp9LADrDb6k=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "datomic-pro-flake" = {
    url = "https://github.com/outskirtslabs/datomic-pro-flake.git";
    rev = "57861874c8cc8008b0b8db91e10cf4d64a730b5b";
    hash = "sha256-g7tbrsHvdaa7IBSXFhOmMhOFLsOGxUqVhQzoTlOr2nQ=";
    refs_hash = "sha256-r0CFtXX5SrgMmC9O3YdQCVk8J0yjMKJMvfCnw0wUq/Q=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "fluent-tooling" = {
    url = "https://github.com/outskirtslabs/fluent-tooling.git";
    rev = "cd5fa0ac663f85faaf2d4205eb8b033c48767669";
    hash = "sha256-JsArNVIKFyWEfpknaYgzRQGkIqx0YsaaL0DCm53aNL4=";
    refs_hash = "sha256-9iMjQHR4rgs/Oj+mORDMuHULztJCThm8IwdLjApa4EE=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "h2o-zig" = {
    url = "https://github.com/outskirtslabs/h2o-zig.git";
    rev = "156c195431778c3458ad54602ce651e2b60462a5";
    hash = "sha256-U8fn6KLYqu0nGMAOFJsG0cqXGWMj+OMxQ1tTlYhS1+k=";
    refs_hash = "sha256-8HVVCH8h/t0XVkaN92qmcuJ+n/AAcD77p3cV1GZuDMQ=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "nixos-hetzner" = {
    url = "https://github.com/outskirtslabs/nixos-hetzner.git";
    rev = "62c6e1ef4c943bef5453238fb2b43b57b400edd6";
    hash = "sha256-pNVXNdB2fs1BS0qahkTYWn+mSuWSja9CDp4FuXQ7bGg=";
    refs_hash = "sha256-+0f6pBV4qwTBjcgZyOFfFeyviloJJ39RjhRqOaPUiDk=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "nixos-hetzner-demo" = {
    url = "https://github.com/outskirtslabs/nixos-hetzner-demo.git";
    rev = "1d522e4ab2298623d8dd8f8340ceb4b89592d673";
    hash = "sha256-0uqOcIP7mq6BSvXJ6oBT5w15uk7lepaTLanLwZyZmko=";
    refs_hash = "sha256-hcXnyZgLTFzmS+ZORGs1dOT6UeY4w7/bTq1bz/GXFlE=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "ol.clave" = {
    url = "https://github.com/outskirtslabs/clave.git";
    rev = "a7b69296b4c2353c147cb509c9e81675956bc23b";
    hash = "sha256-y+Fs7oZ9+2gpfThdfTKcWkIDiejgrTOnUbWmKbiYafc=";
    refs_hash = "sha256-rp9ebE7fjS4Kyc+4UKwBOen20LveNpV8I6ZOaUoFJ0s=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "ol.dirs" = {
    url = "https://github.com/outskirtslabs/dirs.git";
    rev = "0aaf5535aa0d99d220b45550404e33be87191b66";
    hash = "sha256-UtRSxlqdwwunYohkqz7j4Harc1Vhagx97NIqh44bNOE=";
    refs_hash = "sha256-VVPlgeyxdCH3fo/r1Oa0i0tiPW1ynFi6Wg9ITtLx08Y=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "ol.llx" = {
    url = "https://github.com/outskirtslabs/llx.git";
    rev = "70717b489022d6b1b5f4aef52a0128ca1ebf1d99";
    hash = "sha256-dUnP0xzvCtZzhl2CAhbYNaX4xl/+/a4TyqidwqAf+Q0=";
    refs_hash = "sha256-WVQiBpBDUFxqDizw/zORF3hS6gCIp1xPmMAkxF6OWpM=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "ol.protocol53" = {
    url = "https://github.com/outskirtslabs/protocol53.git";
    rev = "968a90ecfe1884fc2fb9b07a395f2a48514ab5b2";
    hash = "sha256-SElIAKcix8ihybttAd6hlVzPRc0FoTdiq7/L5LU58xw=";
    refs_hash = "sha256-8tyyg+sW9ouc1HTB2Wy+yDwNSRLTyQduGS0koNAZe48=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "ol.sfv" = {
    url = "https://github.com/outskirtslabs/sfv.git";
    rev = "0267153d7b207cc118df2324dab74210da5ed8ad";
    hash = "sha256-Q0X6CSlCASbPcGUVFoUYKpo4A3YEebgHgREs/70Gplg=";
    refs_hash = "sha256-T3KmrKjzz1TJn27rPygV8my3U9XVcBapDXaaZ9RBqfc=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "ol.sops" = {
    url = "https://github.com/outskirtslabs/sops.git";
    rev = "344bbcec229fb68750e08bfe4ad12ca92d368bd1";
    hash = "sha256-3Avs6/3leGAdTHj8c9eZO8dMHkJFJ+J8B63aShPr4BU=";
    refs_hash = "sha256-lyoyE3cH3TZ1A35oPPxy/popvLK1Btl9QYczQfk1zV8=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "ol.trixnity" = {
    url = "https://github.com/outskirtslabs/trixnity-clj.git";
    rev = "b570f9c824f58668b7562ed503f5d6e8475aa17f";
    hash = "sha256-JKPNreFI2nMy+akmzyYSVwOFvIufDBKlldf9MLhnJQc=";
    refs_hash = "sha256-IuoG6+r2teqbLjHfVJlUMDzKcFFNOZwQ2PSaXBPU7oE=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "ol.vips" = {
    url = "https://github.com/outskirtslabs/vips.git";
    rev = "ca66dab7ef627fd58ab3a324d8e9ec4b86ea3fc0";
    hash = "sha256-nNTl7y/k3BvYGV0BCuPi9snm1p6X/o0HVWVG4q/4ltU=";
    refs_hash = "sha256-P5JEXbZZNUjgYHBtnMNd0zt6FO6FqfbNS27smI3O4wI=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };
}
