{
# This file is automatically generated, do not edit UNLESS you are adding a _new_ project
  "client-ip" = {
    url = "https://github.com/outskirtslabs/client-ip.git";
    rev = "0c84d74eff7dc03033dc0af3b3bb6d0b96c2a39c";
    hash = "sha256-Cx8Ro+EdAduPQEWiH+yw6LJHSlZEqNDicOov6kSxw/4=";
    refs_hash = "sha256-cgowqGZlEAPLa6u5bqIwP0fkA44cyMq0Bz6B9GHwzTw=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "datahike-sqlite" = {
    url = "https://github.com/outskirtslabs/datahike-sqlite.git";
    rev = "47a12ab44d08ac106b922e4dfa6bd5a7d43e3802";
    hash = "sha256-MLTlB0ohz6ZqkIQyxAZhfSrdGlJ767NFBuqL12Ai0b0=";
    refs_hash = "sha256-3LQStzeMOQxBaSWNUu6y9/JBNrYHYuewPjmaESILLg4=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "datastar-expressions" = {
    url = "https://github.com/outskirtslabs/datastar-expressions.git";
    rev = "ae625bcc1d9267fc6c76fc96b44c87cdbfc81ac6";
    hash = "sha256-zdlGV6OiXh3Y2v7MJI3vhag+EPOS4w2LPBNRqp1lH7w=";
    refs_hash = "sha256-0dPwTwCgwoZtRREAGuV4WWZjl8bH+xhZxeMpCoJlVBo=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "datomic-pro-flake" = {
    url = "https://github.com/outskirtslabs/datomic-pro-flake.git";
    rev = "69e8d4cda8d88fd2c51b3f354c9b3c76d0cd6bee";
    hash = "sha256-mwjsq+lyRcmb4wMxjYmdp1ACZEIOUpnxHuCQAeCRkw4=";
    refs_hash = "sha256-0u6YGdeYjP3WT/bijvScktGJvqJNfMSYXNK5ExhtXk0=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "h2o-zig" = {
    url = "https://github.com/outskirtslabs/h2o-zig.git";
    rev = "9f5c0684e3ee608399ac201b3559a43065cd3b7f";
    hash = "sha256-swGvKfFGwk9KvkpmSw1lFTWxHICQD/2p0hUW7etkQLw=";
    refs_hash = "sha256-SEIhJUCEb91gPHhpeOpMDOOH5s7s7BUbZDfjrUAm6Xc=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "nixos-hetzner" = {
    url = "https://github.com/outskirtslabs/nixos-hetzner.git";
    rev = "403fda835f15b338488792aee60efb9cb2cb302d";
    hash = "sha256-MHEFL+SeE9ht8w59FYVcDRvCZK3W33HapnQ6qnMHP2o=";
    refs_hash = "sha256-IkBwCC09oXexyCKtQ/3SqvDE8LJfdSMFbNhyWrktNlk=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "nixos-hetzner-demo" = {
    url = "https://github.com/outskirtslabs/nixos-hetzner-demo.git";
    rev = "9486666189fcbf8f65c52f74c1ac70350ee6ac95";
    hash = "sha256-OLv6tB28tPSot5hF7D9fQDVxEj7kNAk0IYunFneA0rE=";
    refs_hash = "sha256-zeFMU/unt+zmgRdIOM/meQgJHmFPP4F0ca2yHJVwSCA=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "ol.dirs" = {
    url = "https://github.com/outskirtslabs/dirs.git";
    rev = "b2b0f75b5564ec5a38a15216ae52c35f169a95b3";
    hash = "sha256-1dqieuBVqB343PB5cbXOPzWiRk4PzQeGM1gPq9kNBdU=";
    refs_hash = "sha256-8N36/Q2wfcrrL7qLBRFCNNnDczTtR7CrSRtJ0w22XQU=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "ol.sfv" = {
    url = "https://github.com/outskirtslabs/sfv.git";
    rev = "17533ae5d4c4cd01014ca5928898221f3aa42997";
    hash = "sha256-JOQ2au56E4US86uBBfCaeua6CTqjhywhy+NIHw0C6Mk=";
    refs_hash = "sha256-//Ajswj0EXI9RFa94GpRAWyIyjyp84ol+gnM4ViF1sg=";
    branches = [ "HEAD" "v{0..9}*" ];
    start_path = "doc";
  };

  "ol.sops" = {
    url = "https://github.com/outskirtslabs/sops.git";
    rev = "39a93982f197be937a0bc16480d0b4e80fa46f91";
    hash = "sha256-WQBGCMItZm+aonXSce7DTgf83ad4QtQviC77xu9ihk4=";
    refs_hash = "sha256-/ger+gm3nDrwWGUE5jd1jK/DIJxeWpJceuK9Tej1Wjg=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };

  "ol.trixnity" = {
    url = "https://github.com/outskirtslabs/trixnity-clj.git";
    rev = "9ffc351980fafb0d6cb804a25d5b2433b71b45f9";
    hash = "sha256-eIu5Iudg8HdGHGfsrBm/CGYDHP26z/8Cg79i25/VUbg=";
    refs_hash = "sha256-XvlHcahJspbw6DIeNVv2ZJD+h8bFWlAfB1OphRpzVMU=";
    branches = [ "HEAD" ];
    start_path = "doc";
  };
}
