= Outskirts Labs developer documentation
:page-role: home

== Hello

++++
<div class="home-box-header">Hi, I'm Casey Link (<a href="https://github.com/Ramblurr">@Ramblurr</a>)</div>
<div class="home-welcome">
<p>Welcome to Outskirts Labs, where I organize my active and maintained open source projects.</p>

<p>My personal GitHub is cluttered with experiments, forks, and random contributions. This space is for the projects I actively maintain.</p>

<p>I am an independent software consultant, serving clients at the edge of technical capacity, sustainable funding, and mainstream attention.</p>

<p>My work focuses on building tools that last without requiring an army of developers or regular rewrites.</p>

<p>If you're a small business, non-profit, or social enterprise needing custom software that fits both your mission and budget, check out <a href="https://outskirtslabs.com">outskirtslabs.com</a> or get in touch directly <a href="mailto:casey@outskirtslabs.com">casey@outskirtslabs.com</a></p>

<div class="signoff">
<p>Cheers,</p>
<p>Casey Link</p>
</div>

<div class="ps">
<p>p.s. For the curious and fellow Clojurians, my personal homepage at <a href="https://casey.link">casey.link</a> may be of interest.</p>
</div>
</div>
++++

include::partial$home-project-catalog.adoc[]
