= Support

If these projects bring you joy or save you time or money, supporting the work helps me keep them healthy and moving forward (it also helps keep me healthy and moving forward). There are two straightforward ways to do that.

== You are human person

If you are an individual developer or hobbyist, your sponsorship helps fund ongoing maintenance and releases.

Liberapay is my preferred option, because it has lower fees, supports my family, and doesn't enable a monstrous mega-corporation hellbent on world domination.
But I won't judge if you use GitHub Sponsors; it works too.

++++
<div class="support-sponsor-buttons">
  <a href="https://liberapay.com/ramblurr/" class="support-sponsor-button" aria-label="Liberapay donation badge">
    <img src="_images/liberapay.svg" alt="Liberapay donation badge" width="83" height="30">
  </a>
  <a href="https://github.com/sponsors/Ramblurr" class="support-sponsor-button-gh-link" aria-label="Sponsor on GitHub">
    <svg aria-label="Sponsor" class="support-sponsor-button-gh" role="img" version="1.1" viewBox="0 0 114 32" xmlns="http://www.w3.org/2000/svg">
      <rect x=".5" y=".5" width="113" height="31" rx="6" fill="#f6f8fa" stroke="#d0d7de"/>
      <g transform="matrix(.74985 0 0 .74985 17.151 7.0032)" class="gh_heart">
        <path class="gh_heartpath" d="m19.5 12.572-7.5 7.428-7.5-7.428a5 5 0 1 1 7.5-6.566 5 5 0 1 1 7.5 6.566" fill="none" stroke="#bf3989" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"/>
      </g>
      <text class="gh_sponsor" x="69.471596" y="19.700228" fill="#24292f" font-family="'-apple-system', BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif" font-size="13.99px" font-weight="500" stroke-width=".99926" text-anchor="middle">Sponsor</text>
    </svg>
  </a>
</div>
++++

Even small recurring or one-time sponsorships make a real difference, it signals to the community that there is something of value here.

== You are a legal entity

If your company depends on one or more Outskirts Labs projects, I offer paid consulting engagements.

Typical engagements include:

* architecture and implementation guidance
* integrations and custom feature/bug development
* production hardening and reliability work
* team enablement and long-term maintenance planning

To discuss scope, timeline, and budget, email mailto:casey@outskirtslabs.com[casey@outskirtslabs.com].

(p.s. All engagements come with a EU-friendly VAT invoice that will make your bookeeper happy.)
