'use strict'

const { parallel, series } = require('gulp')
const createTask = require('./gulp.d/lib/create-task')
const exportTasks = require('./gulp.d/lib/export-tasks')
const log = require('fancy-log')

const bundleName = 'ui'
const buildDir = 'build'
const srcDir = 'src'
const stageDir = 'public/_'

const task = require('./gulp.d/tasks')
const glob = {
  css: [`${srcDir}/css`],
  js: ['gulpfile.js', 'gulp.d', `${srcDir}/helpers`, `${srcDir}/js`],
  lintJs: ['gulpfile.js', 'gulp.d', `${srcDir}/helpers`, `${srcDir}/js`],
}

const cleanTask = createTask({
  name: 'clean',
  desc: 'Clean files and folders generated by build',
  call: task.remove(['build', 'public']),
})

const lintCssTask = createTask({
  name: 'lint:css',
  desc: 'Lint the CSS source files using Biome',
  call: task.lintCss(glob.css),
})

const lintJsTask = createTask({
  name: 'lint:js',
  desc: 'Lint the JavaScript source files using Biome',
  call: task.lintJs(glob.lintJs),
})

const lintTask = createTask({
  name: 'lint',
  desc: 'Lint the CSS and JavaScript source files',
  call: parallel(lintCssTask, lintJsTask),
})

const formatJsTask = createTask({
  name: 'format:js',
  desc: 'Format and autofix JavaScript source files using Biome',
  call: task.format(glob.js),
})

const formatTask = createTask({
  name: 'format',
  desc: 'Format and autofix JavaScript source files',
  call: formatJsTask,
})

const buildTask = createTask({
  name: 'build',
  desc: 'Build and stage the UI assets for bundling',
  call: task.build(srcDir, stageDir),
})

const bundleBuildTask = createTask({
  name: 'bundle:build',
  call: series(cleanTask, lintTask, buildTask),
})

const bundlePackTask = createTask({
  name: 'bundle:pack',
  desc: 'Create a bundle of the staged UI assets for publishing',
  call: task.pack(
    stageDir,
    buildDir,
    bundleName,
    (bundlePath) => !process.env.CI && log(`Antora option: --ui-bundle-url=${bundlePath}`)
  ),
})

const bundleTask = createTask({
  name: 'bundle',
  desc: 'Clean, lint, build, and bundle the UI for publishing',
  call: series(bundleBuildTask, bundlePackTask),
})

const packTask = createTask({
  name: 'pack',
  desc: '(deprecated; use bundle instead)',
  call: series(bundleTask),
})

module.exports = exportTasks(bundleTask, cleanTask, lintTask, formatTask, buildTask, bundlePackTask, packTask)
